steps:
 # install dependencies for angular app
 - name: "gcr.io/cloud-builders/npm:node-14.10.0"
   args: ["install"]

 # build production ready frontend angular app
 - name: "gcr.io/cloud-builders/npm:node-14.10.0"
   args: [run,build,"--","--configuration=production"]
 
 # copy files from dist folder to cloud storage bucket
 - name: gcr.io/cloud-builders/gsutil
   args: ["-m", "rsync", "-r", "-c", "-d", "./dist/", "gs://sampleeee"]
